name: Sync profile according to Blog and BlogBook repo 
on: 
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REF: github.com/${{github.repository}}
      MYEMAIL: zhewana@qq.com
      MYNAME: ${{github.repository_owner}}
      REPO_NAME: ${{ github.event.repository.name }}

    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      
      - name: Install requairments
        run: |
          python -m pip install feedparser
          python -m pip install pygithub
        
      - name: Sync Blog content to Github Profile
        run: |
          python syncProfile.py ${TOKEN}

      - name: Push all files to master branch
        run: |
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}-bot"
          git remote add ${REPO_NAME} "https://${TOKEN}@${REF}"
          git pull
          git add .
          git commit -m "ZheWana-bot: Sync Github profile." || exit 0
          git push --force ${REPO_NAME}



