name: build-my-book
on: 
  push:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    env:
      TOKEN: ${{ secrets.TOKEN }}
      REF: github.com/${{github.repository}}
      MYEMAIL: zhewana@qq.com
      MYNAME: ${{github.repository_owner}}
      REPO_NAME: ${{ github.event.repository.name }}

    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Install Python and feedparser
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
        run: |
          pip install feedparser
        
      - name: Sync Blog content to Github Profile
        run: |
          python syncProfile.py

      - name: Push all files to master branch
        run: |
          git config --global user.email "${MYEMAIL}"
          git config --global user.name "${MYNAME}-bot"
          git remote add ${REPO_NAME} "https://${TOKEN}@${REF}"
          git add .
          git commit -m "commited by GitHub workflow, built git book"
          git push --force ${REPO_NAME}



